---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3
inputs:
  - name: bre-ci
  - name: source
  - name: dependency
  - name: required_dependency_1
    optional: true
run:
  path: bre-ci/tasks/test-dependency/run
