---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci

inputs:
  - name: core-deps-ci

run:
  path: core-deps-ci/tasks/core-deps-ci/create-bosh-release-reminder-story/run.sh

params:
  TRACKER_API_TOKEN:
  TRACKER_PROJECT_ID:
  TRACKER_RELEASE_REMINDER_MARKER_STORY:
