---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
- name: bre-ci
- name: buildpack-release-tarball
- name: buildpack-release-trigger
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
run:
  path: bre-ci/tasks/update-buildpack-release-trigger/run
