---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/core-deps-ci
inputs:
- name: core-deps-ci
- name: buildpack-release-tarball
- name: buildpack-release-trigger
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
run:
  path: core-deps-ci/tasks/update-buildpack-release-trigger/run
