---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/core-deps-ci
inputs:
  - name: core-deps-ci
  - name: mixins-label
    optional: true
  - name: stacks
    optional: true

outputs:
  - name: build-args

run:
  path: core-deps-ci/tasks/write-build-args-file/run

params:
  BASE_IMAGE:
  STACK_ID:
  STACK:
  IMAGE:
