---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci

inputs:
- name: bre-ci
- name: tiny-run-base-dockerfile
- name: tiny-run-cnb-dockerfile

outputs:
- name: tiny-stack-receipt

run:
  path: bre-ci/tasks/write-tiny-stack-receipt/run
