#@data/values
---
#@ build_stacks = ['cflinuxfs3']
build_stacks: #@ build_stacks
dependencies:
- name: node
  stacks: #@ build_stacks
  version_lines:
    - 10.X.X
    - 12.X.X
    - 13.X.X
  source_type: node
  link: https://github.com/nodejs/Release
#! - name: lifecycle
#!   stacks: #@ build_stacks
#!   version_lines: [latest]
#!   source_type: github-releases
#!   source_params:
#!     repo: buildpack/lifecycle
#!     extension: .tgz
#! - name: org.cloudfoundry.node-engine
#!   stacks: #@ build_stacks
#!   version_lines: [latest]
#!   source_type: github_releases
#!   source_params:
#!     repo: cloudfoundry/node-engine-cnb
#!     fetch_source: true
#!     prerelease: true
#! - name: org.cloudfoundry.nodejs-compat
#!   stacks: #@ build_stacks
#!   version_lines: [latest]
#!   source_type: github_releases
#!   source_params:
#!     repo: cloudfoundry/node-compat-cnb
#!     fetch_source: true
#!     prerelease: true
#! - name: org.cloudfoundry.npm
#!   stacks: #@ build_stacks
#!   version_lines: [latest]
#!   source_type: github_releases
#!   source_params:
#!     repo: cloudfoundry/npm-cnb
#!     fetch_source: true
#!     prerelease: true
#! - name: org.cloudfoundry.yarn
#!   stacks: #@ build_stacks
#!   version_lines: [latest]
#!   source_type: github_releases
#!   source_params:
#!     repo: cloudfoundry/yarn-cnb
#!     fetch_source: true
#!     prerelease: true
