---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
  - name: bre-ci

run:
  path: bre-ci/tasks/test-stack/run

params:
  STACK_ID:
  BUILD_IMAGE:
  RUN_IMAGE:
  GCP_SERVICE_ACCOUNT_KEY:
