#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
resources:
#! Github Repos
- name: buildpacks-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/buildpacks-ci
    branch: master

- name: bre-ci
  type: git
  source:
    uri: git@github.com:pivotal/bre-ci.git
    private_key: ((bre-ci-deploy-key.private_key))
    branch: master

- name: new-cves
  type: git
  source:
    uri: git@github.com:cloudfoundry/public-buildpacks-ci-robots
    branch: master
    paths: [ new-cve-notifications/ubuntu18.04-tiny.yml ]
    private_key: ((public-buildpacks-ci-robots-deploy-key.private_key))

- name: cflinuxfs3-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))
    email: cf-buildpacks-eng@pivotal.io

- name: bionic-image
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

#! CNB stack images
#@ for stack in data.values.stacks:
  #@ for image in stack.images:
- name: #@ "{}-{}-base-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "gcr.io/paketo-buildpacks/" + image
    tag: #@ stack.name
    username: _json_key
    password: ((paketo-gcr-service-account-key))

- name: #@ "{}-{}-cloudfoundry-base-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "cloudfoundry/" + image
    #@ if stack.name != "full-cf":
    tag: #@ stack.name
    #@ else:
    tag: full
    #@ end
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))

- name: #@ "{}-{}-cnb-image-rc".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "gcr.io/cf-buildpacks-releng/{}-rc".format(image)
    #@ if stack.name != "full-cf":
    tag: #@ stack.name + "-cnb"
    #@ else:
    tag: full-cnb-cf
    #@ end
    username: _json_key
    password: ((releng-gcp-service-account-key))

- name: #@ "{}-{}-cnb-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "gcr.io/paketo-buildpacks/" + image
    #@ if stack.name != "full-cf":
    tag: #@ stack.name + "-cnb"
    #@ else:
    tag: full-cnb-cf
    #@ end
    username: _json_key
    password: ((paketo-gcr-service-account-key))

- name: #@ "{}-{}-dockerhub-cnb-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "paketobuildpacks/" + image
    #@ if stack.name != "full-cf":
    tag: #@ stack.name + "-cnb"
    #@ else:
    tag: full-cnb-cf
    #@ end
    username: ((paketo-docker-user.username))
    password: ((paketo-docker-user.password))

- name: #@ "{}-{}-cloudfoundry-cnb-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "cloudfoundry/" + image
    #@ if stack.name != "full-cf":
    tag: #@ stack.name + "-cnb"
    #@ else:
    tag: full-cnb
    #@ end
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))

#! Dockerfiles
- name: #@ "{}-{}-cnb-dockerfile".format(stack.name, image)
  type: git
  source:
    uri: https://github.com/paketo-buildpacks/stacks
    branch: master
    #@ if stack.name != "full-cf":
    paths: #@ [ "{}/cnb/{}/**".format(stack.name, image) ]
    #@ else:
    paths: #@ [ "full/cnb/{}/**".format(image) ]
    #@ end

    #@ if stack.build_base:
- name: #@ "{}-{}-base-dockerfile".format(stack.name, image)
  type: git
  source:
    uri: https://github.com/paketo-buildpacks/stacks
    branch: master
    paths: #@ [ "{}/dockerfile/{}/**".format(stack.name, image) ]
    #@ end

#! Versions
- name: #@ "{}-{}-cnb-version".format(stack.name, image)
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: #@ "stacks/{}-{}-cnb".format(stack.name, image)
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))

- name: #@ "{}-{}-base-version".format(stack.name, image)
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: #@ "stacks/{}-{}-base".format(stack.name, image)
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))
  #@ end

#! Mixins
  #@ if stack.mixins:
- name: #@ stack.name + "-build-mixins"
  type: s3
  source:
    bucket: stack-mixins
    versioned_file: #@ stack.name + "-build-mixins.json"
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))

- name: #@ stack.name + "-run-mixins"
  type: s3
  source:
    bucket: stack-mixins
    versioned_file: #@ stack.name + "-run-mixins.json"
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))
  #@ end
#@ end

#! Tiny's build image is a re-tagged version of the bionic image (and not built from a dockerfile)
#! so it is a special case
- name: tiny-build-cnb-image-rc
  type: registry-image
  source:
    repository: gcr.io/cf-buildpacks-releng/build-rc
    tag: tiny-cnb
    username: _json_key
    password: ((releng-gcp-service-account-key))

- name: tiny-build-cnb-image
  type: registry-image
  source:
    repository: gcr.io/paketo-buildpacks/build
    tag: tiny-cnb
    username: _json_key
    password: ((paketo-gcr-service-account-key))

- name: tiny-build-dockerhub-cnb-image
  type: registry-image
  source:
    repository: paketobuildpacks/build
    tag: tiny-cnb
    username: ((paketo-docker-user.username))
    password: ((paketo-docker-user.password))

- name: tiny-build-cloudfoundry-cnb-image
  type: registry-image
  source:
    repository: cloudfoundry/build
    tag: tiny-cnb
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))

- name: tiny-build-cnb-version
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: stacks/tiny-build-cnb
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))

jobs:
- name: test-tiny
  plan:
    - get: tiny-run-base-dockerfile
      trigger: true
    - get: buildpacks-ci
    - get: new-cves
      trigger: true
    - task: integration-test
      privileged: true
      file: buildpacks-ci/tasks/test-tiny-docker-image/task.yml

- name: update-tiny-build-cnb-image
  public: true
  plan:
    - get: bre-ci
    - get: base-build-cnb-dockerfile
      trigger: true
    - get: base-build-base-image
      trigger: true
      passed:
        - update-base-build-base-image
    - get: version
      resource: tiny-build-cnb-version
      params:
        pre: tiny-cnb
        pre_without_version: true
    - task: write-build-args-file
      file: bre-ci/tasks/write-build-args-file/task.yml
      params:
        BASE_IMAGE: "gcr.io/paketo-buildpacks/build:base"
        STACK_ID: "org.cloudfoundry.stacks.tiny"
    - task: build-tiny-build-cnb-image
      privileged: true
      file: bre-ci/tasks/build-stack-image/task.yml
      input_mapping:
        stacks: base-build-cnb-dockerfile
      params:
        CONTEXT: stacks/base/cnb/build
        BUILD_ARGS_FILE: build-args/args
    - put: tiny-build-cnb-image-rc
      params:
        additional_tags: version/version
        image: image/image.tar
    - task: test-tiny-build-cnb-image-rc
      privileged: true
      file: bre-ci/tasks/test-stack/task.yml
      params:
        STACK_ID: org.cloudfoundry.stacks.tiny
        TAG: tiny-cnb
        IMAGE_TYPE: build
        IMAGE: gcr.io/cf-buildpacks-releng/build-rc:tiny-cnb
        GCP_SERVICE_ACCOUNT_KEY: ((releng-gcp-service-account-key))
    - put: tiny-build-cnb-image
      params:
        additional_tags: version/version
        image: image/image.tar
    - put: tiny-build-dockerhub-cnb-image
      params:
        additional_tags: version/version
        image: image/image.tar
    - put: tiny-build-cloudfoundry-cnb-image
      params:
        additional_tags: version/version
        image: image/image.tar
    - put: version
      resource: tiny-build-cnb-version
      params:
        bump: patch

#@ for stack in data.values.stacks:
  #@ for image in stack.images:
- name: #@ "update-{}-{}-base-image".format(stack.name, image)
  public: true
  plan:
    - get: bre-ci
    #@ if stack.name != "full-cf":
    - get: #@ "{}-{}-base-dockerfile".format(stack.name, image)
      trigger: true
      #@ if stack.name == "tiny":
      passed: [test-tiny]
    - get: new-cves
      passed: [test-tiny]
      trigger: true
      #@ end
    #@ else:
    - get: #@ stack.name + "-image"
      #@ if stack.name == "full-cf":
      resource: cflinuxfs3-image
      #@ end
      trigger: true
      params:
        save: true
    #@ end
    - get: bionic-image
      trigger: true
    - get: version
      resource: #@ "{}-{}-base-version".format(stack.name, image)
      params:
        pre: #@ stack.name
        pre_without_version: true
    #@ if stack.name != "full-cf":
    - task: #@ "build-{}-{}-base-image".format(stack.name, image)
      privileged: true
      file: bre-ci/tasks/build-stack-image/task.yml
      input_mapping:
        stacks: #@ "{}-{}-base-dockerfile".format(stack.name, image)
      params:
        #@ if stack.name != "full-cf":
        CONTEXT: #@ "stacks/{}/dockerfile/{}".format(stack.name, image)
        #@ else:
        CONTEXT: #@ "stacks/full/dockerfile/{}".format(image)
        #@ end
    #@ end
    #@ if stack.name == "full-cf":
    - task: write-tags-list
      file: bre-ci/tasks/write-tags-list/task.yml
      params:
        REMOVE_CF_SUFFIX: true
    #@ end
    - put: #@ "{}-{}-base-image".format(stack.name, image)
      params:
        additional_tags: version/version
        #@ if stack.name != "full-cf":
        image: image/image.tar
        #@ else:
        image: #@ stack.name + "-image/image"
        #@ end
    - put: #@ "{}-{}-cloudfoundry-base-image".format(stack.name, image)
      params:
        #@ if stack.name != "full-cf":
        additional_tags: version/version
        image: image/image.tar
        #@ else:
        additional_tags: tags/tags-cf
        image: #@ stack.name + "-image/image"
        #@ end
    - put: version
      resource: #@ "{}-{}-base-version".format(stack.name, image)
      params:
        bump: patch
  #@ end

  #@ if stack.mixins:
- name: #@ "generate-mixins-labels-{}-cnb-image".format(stack.name)
  public: true
  plan:
    - in_parallel:
      - get: bre-ci
      #@ for image in stack.images:
      - get: #@ "{}-{}-cnb-dockerfile".format(stack.name, image)
        trigger: true
      - get: #@ "{}-{}-base-image".format(stack.name, image)
        trigger: true
        passed: #@ [ "update-{}-{}-base-image".format(stack.name, image) ]
      #@ end
    - in_parallel:
      - task: write-build-package-list
        file: bre-ci/tasks/write-package-list/task.yml
        image: #@ "{}-build-base-image".format(stack.name)
        output_mapping:
          package-list: build-image-package-list
      - task: write-run-package-list
        file: bre-ci/tasks/write-package-list/task.yml
        image: #@ "{}-run-base-image".format(stack.name)
        output_mapping:
          package-list: run-image-package-list
    - task: write-mixins-labels
      file: bre-ci/tasks/write-mixins-labels/task.yml
    - in_parallel:
      - put: #@ stack.name + "-build-mixins"
        params:
          file: build-mixins-label/mixins.json
      - put: #@ stack.name + "-run-mixins"
        params:
          file: run-mixins-label/mixins.json
  #@ end

  #@ for image in stack.images:
- name: #@ "update-{}-{}-cnb-image".format(stack.name, image)
  public: true
  plan:
    - get: bre-ci
    - get: #@ "{}-{}-cnb-dockerfile".format(stack.name, image)
      trigger: true
    - get: #@ "{}-{}-base-image".format(stack.name, image)
      trigger: true
      passed: #@ [ "update-{}-{}-base-image".format(stack.name, image) ]
    - get: version
      resource: #@ "{}-{}-cnb-version".format(stack.name, image)
      params:
        #@ if stack.name != "full-cf":
        pre: #@ stack.name + "-cnb"
        #@ else:
        pre: full-cnb-cf
        #@ end
        pre_without_version: true
    - task: write-build-args-file
      file: bre-ci/tasks/write-build-args-file/task.yml
      params:
        BASE_IMAGE: #@ "gcr.io/paketo-buildpacks/{}:{}".format(image, stack.name)
    - task: #@ "build-{}-{}-cnb-image".format(stack.name, image)
      privileged: true
      file: bre-ci/tasks/build-stack-image/task.yml
      input_mapping:
        stacks: #@ "{}-{}-cnb-dockerfile".format(stack.name, image)
      params:
        #@ if stack.name != "full-cf":
        CONTEXT: #@ "stacks/{}/cnb/{}".format(stack.name, image)
        #@ else:
        CONTEXT: #@ "stacks/full/cnb/{}".format(image)
        #@ end
        BUILD_ARGS_FILE: build-args/args
    - task: write-tags-list
      file: bre-ci/tasks/write-tags-list/task.yml
      params:
        #@ if stack.latest:
        TAGS: latest
        #@ end
        #@ if stack.name == "full-cf":
        REMOVE_CF_SUFFIX: true
        #@ end
    - put: #@ "{}-{}-cnb-image-rc".format(stack.name, image)
      params:
        additional_tags: tags/tags
        image: image/image.tar
    - task: #@ "test-{}-{}-cnb-image-rc".format(stack.name, image)
      privileged: true
      file: bre-ci/tasks/test-stack/task.yml
      params:
        STACK_ID: #@ stack.id
        #@ if stack.name != "full-cf":
        TAG: #@ stack.name + "-cnb"
        IMAGE: #@ "gcr.io/cf-buildpacks-releng/{}-rc:{}-cnb".format(image, stack.name)
        #@ else:
        TAG: full-cnb-cf
        IMAGE: #@ "gcr.io/cf-buildpacks-releng/{}-rc:full-cnb-cf".format(image)
        #@ end
        IMAGE_TYPE: #@ image
        GCP_SERVICE_ACCOUNT_KEY: ((releng-gcp-service-account-key))
    - put: #@ "{}-{}-cnb-image".format(stack.name, image)
      params:
        additional_tags: tags/tags
        image: image/image.tar
    - put: #@ "{}-{}-dockerhub-cnb-image".format(stack.name, image)
      params:
        additional_tags: tags/tags
        image: image/image.tar
    - put: #@ "{}-{}-cloudfoundry-cnb-image".format(stack.name, image)
      params:
        #@ if stack.name != "full-cf":
        additional_tags: tags/tags
        #@ else:
        additional_tags: tags/tags-cf
        #@ end
        image: image/image.tar
    - put: version
      resource: #@ "{}-{}-cnb-version".format(stack.name, image)
      params:
        bump: patch
  #@ end
#@ end

groups:
- name: all
  jobs:
    - test-tiny
    - update-tiny-build-cnb-image
#@ for stack in data.values.stacks:
  #@ for image in stack.images:
    - #@ "update-{}-{}-base-image".format(stack.name, image)
    - #@ "update-{}-{}-cnb-image".format(stack.name, image)
  #@ end
#@ end

#@ for stack in data.values.stacks:
- name: #@ stack.name
  jobs:
  #@ if stack.mixins:
    - #@ "generate-mixins-labels-{}-cnb-image".format(stack.name)
  #@ end
  #@ if stack.name == "tiny":
    - test-tiny
    - update-tiny-build-cnb-image
  #@ end
  #@ for image in stack.images:
    - #@ "update-{}-{}-base-image".format(stack.name, image)
    - #@ "update-{}-{}-cnb-image".format(stack.name, image)
  #@ end
#@ end
