#@data/values
---
images:
- build
- run
stacks:
- name: full-cf
  id: org.cloudfoundry.stacks.cflinuxfs3
  base_images:
    - build
    - run
  build_base: false
  latest: false
  mixins: false
- name: full
  id: io.buildpacks.stacks.bionic
  base_images:
    - build
    - run
  build_base: true
  latest: false
  mixins: true
- name: base
  id: io.buildpacks.stacks.bionic
  base_images:
    - build
    - run
  build_base: true
  latest: true
  mixins: true
- name: tiny
  id: io.paketo.stacks.tiny
  base_images:
    - run
  build_base: true
  latest: false
  mixins: false
