#@data/values
---
stacks:
- name: full-cf
  id: org.cloudfoundry.stacks.cflinuxfs3
  images:
    - build
    - run
  build_base: false
  latest: false
  mixins: false
- name: base
  id: io.buildpacks.stacks.bionic
  images:
    - build
    - run
  build_base: true
  latest: true
  mixins: true
- name: tiny
  id: org.cloudfoundry.stacks.tiny
  images:
    - run
  build_base: true
  latest: false
  mixins: false
