---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci

inputs:
- name: core-deps-ci
- name: receipt
- name: receipt-s3

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
  RECEIPT_FILENAME:

run:
  path: core-deps-ci/tasks/stacks/check-for-receipt-diff/run
