---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci

inputs:
- name: core-deps-ci
- name: build-receipt
- name: run-receipt

outputs:
- name: stack-receipt

run:
  path: core-deps-ci/tasks/stacks/write-stack-receipt/run
