---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
  - name: core-deps-ci
  - name: dependency
  - name: source
  - name: metadata

outputs:
  - name: metadata

run:
  path: core-deps-ci/tasks/write-dependency-metadata/run
