---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci

inputs:
- name: core-deps-ci

outputs:
- name: docker_creds

run:
  path: core-deps-ci/tasks/write-docker-creds/run

params:
  USERNAME:
  PASSWORD:
