#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@yaml/text-templated-strings

#@ def required_dependency_resource_name(required_dependency):
#@   name = required_dependency.name + "-dependency-resource"
#@   if struct.decode(required_dependency).get("version_constraint"):
#@     name = name+"-"+required_dependency.version_constraint
#@   end
#@   return name
#@ end

---
resource_types:
- name: dependency-resource
  type: docker-image
  source:
    repository: cfbuildpacks/dependency-resource
- name: external-dependency-resource
  type: docker-image
  source:
    repository: cfbuildpacks/external-dependency-resource

resources:
- name: bre-ci
  type: git
  source:
    uri: git@github.com:pivotal/bre-ci.git
    branch: master
    private_key: ((bre-ci-deploy-key.private_key))
- name: buildpacks-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/buildpacks-ci.git
    branch: master
- name: binary-builder
  type: git
  source:
    uri: https://github.com/cloudfoundry/binary-builder.git
    branch: master

#@ for dependency in data.values.dependencies:
- name: #@ dependency.name + "-source"
  type: external-dependency-resource
  source:
    type: #@ dependency.source_type
    github_access_token: ((buildpacks-github-token))

- name: #@ dependency.name + "-dependency-resource"
  type: dependency-resource
  source:
    bucket: pivotal-buildpacks
    access_key_id: ((pivotal-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-buildpacks-s3-secret-key))
    region_name: "us-east-1"
    s3_prefix: #@ "deps/" + dependency.name
    dependency_name: #@ dependency.name
#@ end

#@ for dependency in data.values.dependencies:
  #@ for required_dependency in struct.encode(struct.decode(dependency).get('requires', [])):
    #@ if struct.decode(required_dependency).get("version_constraint"):
- name: #@ required_dependency_resource_name(required_dependency)
  type: dependency-resource
  source:
    bucket: pivotal-buildpacks
    access_key_id: ((pivotal-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-buildpacks-s3-secret-key))
    region_name: "us-east-1"
    s3_prefix: #@ "deps/" + required_dependency.name
    dependency_name: #@ required_dependency.name
    version_constraint: #@ required_dependency.version_constraint
    #@ end
  #@ end
#@ end

#@ for stack in data.values.build_stacks:
- name: #@ stack + "-image"
  type: docker-image
  source:
    repository: #@ "cloudfoundry/" + stack
#@ end

jobs:
#@ for dependency in data.values.dependencies:
- name: #@ "build-" + dependency.name
  plan:
  - in_parallel:
    - get: bre-ci
    - get: buildpacks-ci
    - get: binary-builder
  #@ for required_dependency in struct.encode(struct.decode(dependency).get('requires', [])):
    - get: #@ required_dependency_resource_name(required_dependency)
  #@ end
    - get: source
      resource: #@ dependency.name + "-source"
      trigger: true
  #@ for stack in dependency.stacks:
    - get: #@ stack + "-image"
  #@ end
  - in_parallel:
  #@ for stack in dependency.stacks:
    #@ if struct.decode(dependency).get('skip_build', False):
    - task: #@ "split-dependency-and-metadata-" + stack
      file: bre-ci/tasks/split-dependency-and-metadata/task.yml
      output_mapping:
        dependency: #@ stack + "-dependency"
        metadata: #@ stack + "-metadata"
    #@ else:
    - do:
      - task: #@ "build-binary-" + stack
        image: #@ stack + "-image"
        file: buildpacks-ci/tasks/build-binary-new/build.yml
        output_mapping:
          artifacts: #@ stack + "-dependency"
          dep-metadata: #@ stack + "-metadata"
        params:
          STACK: #@ stack
          SKIP_COMMIT: true
      - task: #@ "run-tests-" + stack
        file: bre-ci/tasks/test-dependency/task.yml
        input_mapping:
          dependency: #@ stack + "-dependency"
      #@ for index in range(len(struct.decode(dependency).get('requires', []))):
          required_dependency_(@= str(index+1) @): #@ required_dependency_resource_name(dependency.requires[index])
      #@ end
    #@ end
  #@ end
  - in_parallel:
  #@ for stack in dependency.stacks:
    - put: #@ "{}-{}-dependency-resource".format(dependency.name, stack)
      resource: #@ dependency.name + "-dependency-resource"
      params:
        dependency_file: #@ stack + "-dependency/*"
        metadata_file: #@ stack + "-metadata/*.json"
  #@ end
#@ end
