#@data/values
---
dependencies:
- name: appdynamics
  source_type: appdynamics
  skip_test: true
- name: CAAPM
  source_type: CAAPM
  skip_test: true
- name: composer
  source_type: composer
  skip_test: true
- name: go
  source_type: go
- name: httpd
  source_type: httpd
  skip_test: true
- name: nginx
  source_type: nginx
- name: node
  source_type: node
- name: php
  source_type: php
- name: yarn
  source_type: yarn
  requires:
  - name: node
