#@ load("@ytt:data", "data")
#@ load("@ytt:struct", "struct")
#@yaml/text-templated-strings

#@ def required_dependency_name(required_dependency):
#@   name = required_dependency.name + "-dependency"
#@   if struct.decode(required_dependency).get("version_constraint"):
#@     name = name + "-" + required_dependency.version_constraint
#@   end
#@   return name
#@ end

#@ def get_mixins(dependency):
#@   mixin_list = ""
#@   for mixin in struct.encode(struct.decode(dependency).get('mixins', [])):
#@     mixin_list = mixin_list + mixin + ","
#@   end
#@   length = len(mixin_list)
#@   return mixin_list[0:length - 1]
#@ end

---
resource_types:
- name: external-dependency-resource
  type: docker-image
  source:
    repository: cfbuildpacks/external-dependency-resource

resources:
- name: bre-ci
  type: git
  source:
    uri: git@github.com:pivotal/bre-ci.git
    branch: master
    private_key: ((bre-ci-deploy-key.private_key))
- name: buildpacks-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/buildpacks-ci.git
    branch: master
- name: binary-builder
  type: git
  source:
    uri: https://github.com/cloudfoundry/binary-builder.git
    branch: master

#@ for dependency in data.values.dependencies:
- name: #@ dependency.name + "-source"
  type: external-dependency-resource
  source:
    type: #@ dependency.source_type
    github_access_token: ((buildpacks-github-token))

- name: #@ dependency.name + "-dependency"
  type: s3
  source:
    bucket: test-delete-me-bp
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))
    region_name: "us-east-1"
    regexp: #@ "deps/" + dependency.name + "/(.*)"

- name: #@ dependency.name + "-metadata"
  type: s3
  source:
    bucket: test-delete-me-bp
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))
    region_name: "us-east-1"
    regexp: #@ "metadata/" + dependency.name + "/(.*)"
#@ end

jobs:
#@ for dependency in data.values.dependencies:
- name: #@ "build-" + dependency.name
  plan:
  - in_parallel:
    - get: buildpacks-ci
    - get: binary-builder
    - get: source
      resource: #@ dependency.name + "-source"
      trigger: true
  - task: build-binary
    file: buildpacks-ci/tasks/build-binary-new/build.yml
    output_mapping:
      artifacts: dependency
    params:
      STACK: bionic
      SKIP_COMMIT: true
  - put: #@ dependency.name + "-dependency"
    params:
      file: dependency/*

  #@ if not struct.decode(dependency).get('skip_test', False):
- name: #@ "test-" + dependency.name
  plan:
    - in_parallel:
      - get: dependency
        resource: #@ dependency.name + "-dependency"
        passed: #@ [ "build-" + dependency.name ]
        trigger: true
      - get: bre-ci
      #@ for required_dependency in struct.encode(struct.decode(dependency).get('requires', [])):
      - get: #@ required_dependency_name(required_dependency)
      #@ end
      - get: source
        resource: #@ dependency.name + "-source"
        passed: #@ [ "build-" + dependency.name ]
    - task: run-tests
      file: bre-ci/tasks/test-dependency/task.yml
      input_mapping:
        #@ for index in range(len(struct.decode(dependency).get('requires', []))):
        required_dependency_(@= str(index+1) @): #@ required_dependency_name(dependency.requires[index])
        #@ end
      params:
        MIXINS: #@ get_mixins(dependency)
  #@ end

- name: #@ "upload-metadata-" + dependency.name
  plan:
    - in_parallel:
      - get: dependency
        resource: #@ dependency.name + "-dependency"
        #@ if not struct.decode(dependency).get('skip_test', False):
        passed: #@ [ "test-" + dependency.name ]
        #@ else:
        passed: #@ [ "build-" + dependency.name ]
        #@ end
        trigger: true
      - get: source
        resource: #@ dependency.name + "-source"
        #@ if not struct.decode(dependency).get('skip_test', False):
        passed: #@ [ "test-" + dependency.name ]
        #@ else:
        passed: #@ [ "build-" + dependency.name ]
        #@ end
      - get: bre-ci
    - task: write-dependency-metadata
      file: bre-ci/tasks/write-dependency-metadata/task.yml
      params:
        STACK_ID: io.buildpacks.stacks.bionic
        MIXINS: #@ get_mixins(dependency)
    - put: #@ dependency.name + "-metadata"
      params:
        file: metadata/*.json
#@ end

groups:
- name: all
  jobs:
    #@ for dependency in data.values.dependencies:
     - #@ "build-" + dependency.name
      #@ if not struct.decode(dependency).get('skip_test', False):
     - #@ "test-" + dependency.name
      #@ end
     - #@ "upload-metadata-" + dependency.name
    #@ end

#@ for dependency in data.values.dependencies:
- name: #@ dependency.name
  jobs:
    - #@ "build-" + dependency.name
  #@ if not struct.decode(dependency).get('skip_test', False):
    - #@ "test-" + dependency.name
  #@ end
    - #@ "upload-metadata-" + dependency.name
#@ end
