#@data/values
---
dependencies:
- name: appdynamics
  source_type: appdynamics
  skip_test: true
- name: CAAPM
  source_type: CAAPM
  skip_test: true
- name: composer
  source_type: composer
  skip_test: true
- name: go
  source_type: go
- name: httpd
  source_type: httpd
  mixins:
  - libexpat1
- name: nginx
  source_type: nginx
- name: node
  source_type: node
- name: php
  source_type: php
  mixins:
  - libargon2-0
  - libcurl4
  - libgd3
  - libmagickwand-6.q16-3
  - libonig4
  - libxml2
  - libyaml-0-2
- name: yarn
  source_type: yarn
  requires:
  - name: node
