#@data/values
---
#@ build_stacks = ['cflinuxfs3']
build_stacks: #@ build_stacks
dependencies:
- name: node
  stacks: #@ build_stacks
  source_type: node
  requires: []
- name: yarn
  stacks: #@ build_stacks
  source_type: yarn
  requires:
    - node
- name: go
  stacks: #@ build_stacks
  source_type: go
  requires: []
- name: php
  stacks: #@ build_stacks
  source_type: php
  requires: []
