#@data/values
---
dependencies:
- name: bundler
  source_type: bundler
  requires:
  - name: ruby
- name: CAAPM
  source_type: CAAPM
  skip_test: true
- name: composer
  source_type: composer
  skip_test: true
- name: dotnet-aspnetcore
  source_type: dotnet-aspnetcore
  requires:
  - name: dotnet-sdk
- name: dotnet-runtime
  source_type: dotnet-runtime
  requires:
  - name: dotnet-sdk
- name: dotnet-sdk
  source_type: dotnet-sdk
- name: go
  source_type: go
- name: httpd
  source_type: httpd
  mixins:
  - libexpat1
- name: icu
  source_type: icu
- name: nginx
  source_type: nginx
- name: node
  source_type: node
- name: php
  source_type: php
  mixins:
  - libargon2-0
  - libcurl4
  - libedit2
  - libgd3
  - libmagickwand-6.q16-3
  - libonig4
  - libxml2
  - libyaml-0-2
- name: pip
  source_type: pip
  requires:
  - name: python
- name: pipenv
  source_type: pipenv
  requires:
  - name: python
- name: python
  source_type: python
- name: ruby
  source_type: ruby
- name: yarn
  source_type: yarn
  requires:
  - name: node
