#@data/values
---
dependencies:
- name: bundler
  requires:
  - name: ruby
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: CAAPM
  skip_test: true
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: composer
  skip_test: true
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: dotnet-aspnetcore
  requires:
  - name: dotnet-sdk
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: dotnet-runtime
  requires:
  - name: dotnet-sdk
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: dotnet-sdk
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: go
  stacks:
  - id: io.buildpacks.stacks.bionic
  - id: io.paketo.stacks.tiny
- name: httpd
  stacks:
  - id: io.buildpacks.stacks.bionic
    mixins:
    - libexpat1
- name: icu
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: nginx
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: node
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: php
  stacks:
  - id: io.buildpacks.stacks.bionic
    mixins:
    - libargon2-0
    - libcurl4
    - libedit2
    - libgd3
    - libmagickwand-6.q16-3
    - libonig4
    - libxml2
    - libyaml-0-2
- name: pip
  requires:
  - name: python
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: pipenv
  requires:
  - name: python
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: python
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: ruby
  stacks:
  - id: io.buildpacks.stacks.bionic
- name: yarn
  requires:
  - name: node
  stacks:
  - id: io.buildpacks.stacks.bionic
