#@data/values
---
#@ build_stacks = ['cflinuxfs3']
build_stacks: #@ build_stacks
dependencies:
- name: node
  stacks: #@ build_stacks
  source_type: node
- name: yarn
  stacks: #@ build_stacks
  source_type: yarn
  requires:
    - node
- name: go
  stacks: #@ build_stacks
  source_type: go
- name: php
  stacks: #@ build_stacks
  source_type: php
- name: nginx
  stacks: #@ build_stacks
  source_type: nginx
