---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
- name: bre-ci
run:
  path: bre-ci/tasks/check-proprietary-dependencies/run
params:
  CNB_NAME:
  CNB_ORG:
  GITHUB_TOKEN:
  TRACKER_API_TOKEN:
  TRACKER_PROJECT_ID:
