resources:
- name: bre-ci-dockerfile
  type: git
  source:
    uri: git@github.com:pivotal/bre-ci.git
    private_key: ((bre-ci-deploy-key.private_key))
    paths: [Dockerfile]

- name: bre-ci-image
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
    username: ((cfbuildpacks-dockerhub-user.username))
    password: ((cfbuildpacks-dockerhub-user.password))

jobs:
- name: build-bre-ci-image
  plan:
  - in_parallel:
    - get: bre-ci-dockerfile
      trigger: true
  - put: bre-ci-image
    params:
      build: bre-ci-dockerfile
