resources:
- name: core-deps-ci-dockerfile
  type: git
  source:
    uri: git@github.com:cloudfoundry/core-deps-ci.git
    private_key: ((core-deps-ci-deploy-key.private_key))
    paths: [Dockerfile]

- name: core-deps-ci-image
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
    username: ((coredeps-dockerhub-user.username))
    password: ((coredeps-dockerhub-user.password))

jobs:
- name: build-core-deps-ci-image
  plan:
  - in_parallel:
    - get: core-deps-ci-dockerfile
      trigger: true
  - put: core-deps-ci-image
    params:
      build: core-deps-ci-dockerfile
