---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
- name: core-deps-ci
- name: cf-deployment-concourse-tasks
- name: toolsmiths-env
outputs:
- name: cats-integration-config
run:
  path: core-deps-ci/tasks/create-cats-integration-config/run
