---
  platform: windows
  
  inputs:
    - name: core-deps-ci
    - name: stacks
    - name: build-args
      optional: true
    - name: docker_creds
      optional: true

  run:
    path: bash
    args:
      - core-deps-ci\tasks\stacks-windows\build-stack-image\run
  
  outputs:
    - name: image

  params:
    CONTEXT:
    BUILD_ARGS_FILE:
    DOCKER_CONFIG: docker_creds
