---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
    username: ((coredeps-dockerhub-user.username))
    password: ((coredeps-dockerhub-user.password))
inputs:
  - name: core-deps-ci
  - name: bp-envs
params:
  CI_INSTANCE:
run:
  path: core-deps-ci/tasks/core-deps-ci/recreate-workers/run.sh
