---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
  - name: core-deps-ci
  - name: bp-envs
params:
  CI_INSTANCE:
run:
  path: core-deps-ci/tasks/core-deps-ci/recreate-workers/run.sh
