#@data/values
---
concourse_url: https://buildpacks.ci.cf-app.com
cnb_builder_uri: git@github.com:paketo-buildpacks/builder
cnb_builder_private_key: ((builder-deploy-key.private_key))
pipeline_name: cnb-builder
destination_registry_username: _json_key
destination_registry_password: ((paketo-gcr-service-account-key))
supported_lifecycle_versions:
  - latest
  - n-1
  - n-2
images:
  - build
  - run
stacks:
- name: cflinuxfs3
  tag: full-cf
- name: bionic
  tag: base
- name: tiny
  tag: tiny
builders:
- name: tiny
  stack: tiny
  version_key: tiny
  repository: gcr.io/paketo-buildpacks/builder
  latest: false
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "io.paketo.stacks.tiny"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:tiny-cnb"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:tiny-cnb"
  - name: RUN_IMAGE_MIRRORS
    value: "registry.hub.docker.com/paketobuildpacks/run:tiny-cnb"
  - name: DESCRIPTION
    value: "Tiny base image (bionic build image, distroless run image) with buildpacks for Golang"
- name: base
  stack: bionic
  version_key: base
  repository: gcr.io/paketo-buildpacks/builder
  latest: false
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "io.buildpacks.stacks.bionic"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:base-cnb"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:base-cnb"
  - name: RUN_IMAGE_MIRRORS
    value: "registry.hub.docker.com/paketobuildpacks/run:base-cnb"
  - name: DESCRIPTION
    value: "Ubuntu bionic base image with buildpacks for Java, NodeJS, Golang, and HTTPD"
- name: full-cf
  stack: cflinuxfs3
  version_key: full-cf
  repository: gcr.io/paketo-buildpacks/builder
  latest: true
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "org.cloudfoundry.stacks.cflinuxfs3"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:full-cnb-cf"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:full-cnb-cf"
  - name: RUN_IMAGE_MIRRORS
    value: "registry.hub.docker.com/paketobuildpacks/run:full-cnb-cf"
  - name: DESCRIPTION
    value: "cflinuxfs3 base image with buildpacks for Java, .NET, NodeJS, Golang, PHP, HTTPD and NGINX"
git_cnbs: []
github_cnbs:
- name: httpd
  org: paketo-buildpacks
  repo: httpd
  skip_stack:
    - "tiny"
- name: nginx
  org: paketo-buildpacks
  repo: nginx
  skip_stack:
    - "tiny"
published_cnbs:
- name: dotnet-core
  repo: "gcr.io/paketo-buildpacks/dotnet-core"
  skip_stack:
    - "tiny"
- name: go
  repo: "gcr.io/paketo-buildpacks/go"
- name: java
  repo: "gcr.io/paketo-buildpacks/java"
  skip_stack:
    - "tiny"
- name: nodejs
  repo: "gcr.io/paketo-buildpacks/nodejs"
  skip_stack:
    - "tiny"
- name: php
  repo: "gcr.io/paketo-buildpacks/php"
  skip_stack:
    - "bionic"
    - "tiny"
