#@ load("@ytt:data", "data")
#@yaml/text-templated-strings

#@ def generate_tags(builder, version):
#@   if version != "latest":
#@     return ""
#@   end
#@   tags = builder.stack
#@   for stack in data.values.stacks:
#@     if stack.name == builder.stack:
#@       tags += " " + stack.tag
#@     end
#@   end
#@   if builder.latest:
#@     tags += " latest"
#@   end
#@   return tags
#@ end

#@ def get_params(builder):
#@   params_dict = {}
#@   for param in builder.builder_image_params:
#@     params_dict.update({param.name: param.value})
#@   end
#@   return params_dict
#@ end

#@ def is_enterprise_builder(builder):
#@   for param in builder.builder_image_params:
#@     if param.name == "ENTERPRISE":
#@       if param.value == True:
#@         return True
#@       end
#@     end
#@   end
#@   return False
#@ end

#@ def cnbs_for_builder(builder):
#@   cnbs = []
#@   for cnb in data.values.cnbs:
#@     include_cnb = True
#@     for stack in cnb.skip_stack:
#@       if stack == builder.stack:
#@         include_cnb = False
#@       end
#@     end
#@     if include_cnb:
#@       cnbs.append(cnb)
#@     end
#@   end
#@   return cnbs
#@ end

#@ def get_cnb_source_config(cnb):
#@   config = {"uri": cnb.git_repo, "tag_filter": 'v*'}
#@   if hasattr(cnb, "private_key"):
#@     config.update({"private_key": cnb.private_key})
#@   else:
#@     config.update({"private_key": "((cf-buildpacks-eng-github-ssh-key.private_key))"})
#@   end
#@   return config
#@ end

---
resource_types:
  - name: cron
    type: docker-image
    source:
      repository: cfbuildpacks/cron-resource

resources:
- name: buildpacks-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/buildpacks-ci
    branch: master

- name: bre-ci
  type: git
  source:
    uri: git@github.com:pivotal/bre-ci.git
    private_key: ((bre-ci-deploy-key.private_key))
    branch: master

- name: cnb-builder
  type: git
  source:
    uri: #@ data.values.cnb_builder_uri
    private_key: #@ data.values.cnb_builder_private_key
    branch: master

#@ for cnb in data.values.cnbs:
- name: #@ cnb.name + "-cnb-release"
  type: git
  check_every: 15m #! to avoid thundering herd of cnb autobumping
  source: #@ get_cnb_source_config(cnb)
#@ end

- name: packager
  type: git
  source:
    uri: https://github.com/cloudfoundry/libcfbuildpack
    branch: master

- name: pack-release
  type: github-release
  source:
    user: buildpacks
    repository: pack
    access_token: ((buildpacks-github-token))
    globs: ['*-linux.tgz']

- name: cnb-lifecycle-release
  type: github-release
  source:
    repository: lifecycle
    user: buildpacks
    access_token: ((buildpacks-github-token))

#@ for version in data.values.supported_lifecycle_versions:
- name: #@ "cnb-lifecycle-release-" + version
  type: github-release
  source:
    repository: lifecycle
    user: buildpacks
    access_token: ((buildpacks-github-token))
#@ end

- name: lifecycle-metadata-file
  type: s3
  source:
    bucket: lifecycle-metadata
    access_key_id: ((lifecycle-metadata-s3-access-key))
    secret_access_key: ((lifecycle-metadata-s3-secret-key))
    versioned_file: lifecycle-metadata.json

#! Versions
#@ for builder in data.values.builders:
- name: #@ builder.version_key + "-version"
  type: semver
  source:
    initial_version: 0.0.1
    bucket: cnb-versions
    key: #@ "builder/" + builder.version_key
    access_key_id: ((pivotal-offline-buildpacks-s3-access-key))
    secret_access_key: ((pivotal-offline-buildpacks-s3-secret-key))

#! Docker Images
  #@ for version in data.values.supported_lifecycle_versions:
- name: #@ builder.name + "-platform-api-" + version + "-builder-image"
  type: registry-image
  source:
    repository: #@ builder.repository
    tag: #@ builder.name + "-platform-api-" + version
    username: #@ data.values.destination_registry_username
    password: #@ data.values.destination_registry_password

    #@ if builder.repository == "gcr.io/paketo-buildpacks/builder":
- name: #@ builder.name + "-platform-api-" + version + "-cloudfoundry-builder-image"
  type: registry-image
  source:
    repository: cloudfoundry/cnb
    tag: #@ builder.name + "-platform-api-" + version
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))
    #@ end

- name: #@ builder.name + "-platform-api-" + version + "-rc-image"
  type: registry-image
  source:
    repository: gcr.io/cf-buildpacks/builder-rcs
    tag: #@ builder.name + "-platform-api-" + version
    username: _json_key
    password: ((gcp-service-account-key))
  #@ end
#@ end

#@ for stack in data.values.stacks:
  #@ for image in data.values.images:
- name: #@ "{}-{}-cnb-image".format(stack.name, image)
  type: registry-image
  source:
    repository: #@ "cloudfoundry/" + image
    tag: #@ stack.tag + "-cnb"
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))
  #@ end
#@ end

- name: ci-image
  type: registry-image
  source:
    repository: cfbuildpacks/ci
    username: ((buildpacks-docker-user.username))
    password: ((buildpacks-docker-user.password))

jobs:
- name: pin-cnb-lifecycle-releases
  plan:
  - in_parallel:
    - get: bre-ci
    - get: lifecycle-metadata-file
    - get: lifecycle
      resource: cnb-lifecycle-release
      trigger: true
#@ for version in data.values.supported_lifecycle_versions:
    - get: #@ "cnb-lifecycle-release-" + version
#@ end
  - task: get-platform-api-version
    file: bre-ci/tasks/get-platform-api-version/task.yml
  - task: update-lifecycle-metadata
    file: bre-ci/tasks/update-lifecycle-platform-api-mappings/task.yml
  - task: pin-lifecycle-versions
    file: bre-ci/tasks/pin-lifecycle-versions/task.yml
    params:
      CONCOURSE_URL: #@ data.values.concourse_url
      CONCOURSE_USERNAME: ((concourse_user.username))
      CONCOURSE_PASSWORD: ((concourse_user.password))
      CONCOURSE_TEAM: releng
  - put: lifecycle-metadata-file
    params:
      file: lifecycle-metadata-file/lifecycle-metadata.json

#@ for version in data.values.supported_lifecycle_versions:
  #@ for builder in data.values.builders:
- name: #@ "create-{}-builder-rc-platform-api-{}".format(builder.name, version)
  plan:
    - in_parallel:
      - get: bre-ci
      - get: buildpacks-ci
      - get: ci-image
      - get: packager
      - get: pack
        resource: pack-release
        trigger: true
      - get: cnb-lifecycle-release
        passed: [ pin-cnb-lifecycle-releases ]
      - get: lifecycle
        resource: #@ "cnb-lifecycle-release-" + version
        trigger: true
      - get: #@ builder.stack + "-build-cnb-image"
        trigger: true
      - get: #@ builder.stack + "-run-cnb-image"
        trigger: true
    #@ for cnb in cnbs_for_builder(builder):
      - get: #@ cnb.name + "-cnb"
        resource: #@ cnb.name + "-cnb-release"
        trigger: true
    #@ end
      - get: cnb-builder
      - get: version
        resource: #@ builder.version_key + "-version"
        params:
          pre: rc
    - task: get-cnb-sources
      image: ci-image
      config:
        platform: linux
        inputs:
    #@ for cnb in cnbs_for_builder(builder):
          - name: #@ cnb.name + "-cnb"
    #@ end
        outputs:
          - name: sources
        run:
          path: bash
          args:
            - -cl
            - cp -r *-cnb sources/
    - task: create-builder-image
      image: ci-image
      file: buildpacks-ci/tasks/create-builder/task.yml
      privileged: true
      params: #@ get_params(builder)
    - task: get-platform-api-version
      file: bre-ci/tasks/get-platform-api-version/task.yml
    - task: write-tags-list
      file: bre-ci/tasks/write-tags-list/task.yml
      params:
        TAGS: #@ generate_tags(builder, version)
        STACK: #@ builder.name
    - put: #@ builder.name + "-platform-api-" + version + "-rc-image"
      params:
        additional_tags: tags/tags
        image: builder-image/builder.tgz
    - put: version
      resource: #@ builder.version_key + "-version"
      params:
        file: version/version

- name: #@ "test-{}-builder-rc-platform-api-{}".format(builder.name, version)
  plan:
    - in_parallel:
      - get: buildpacks-ci
      - get: ci-image
      - get: lifecycle
        resource: #@ "cnb-lifecycle-release-" + version
        passed: #@ [ "create-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
      - get: version
        resource: #@ builder.version_key + "-version"
        passed: #@ [ "create-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
      - get: builder-image
        resource: #@ builder.name + "-platform-api-" + version + "-rc-image"
        trigger: true
        passed: #@ [ "create-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
        params:
          format: oci
      - get: pack
        resource: pack-release
      - get: cnb-builder
    - task: smoke-test-builder
      image: ci-image
      file: buildpacks-ci/tasks/test-builder/task.yml
      privileged: true
      params:
        STACK: #@ builder.name
        REPO: gcr.io/cf-buildpacks/builder-rcs
        RUN_IMAGE: #@ get_params(builder).get("RUN_IMAGE")

- name: #@ "ship-{}-builder-platform-api-{}".format(builder.name, version)
  plan:
    - in_parallel:
      - get: ci-image
      - get: bre-ci
      - get: buildpacks-ci
      - get: lifecycle
        resource: #@ "cnb-lifecycle-release-" + version
        passed: #@ [ "test-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
      - get: #@ builder.name + "-platform-api-" + version + "-rc-image"
        passed: #@ [ "test-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
        trigger: true
        params:
          format: oci
      - get: version
        resource: #@ builder.version_key + "-version"
        passed: #@ [ "test-{}-builder-rc-platform-api-{}".format(builder.name, version) ]
        params:
          bump: final
          pre: #@ builder.name
          pre_without_version: true
    - task: get-platform-api-version
      file: bre-ci/tasks/get-platform-api-version/task.yml
    - task: write-tags-list
      image: ci-image
      file: bre-ci/tasks/write-tags-list/task.yml
      params:
        TAGS: #@ generate_tags(builder, version)
        STACK: #@ builder.name
    - put: #@ builder.name + "-platform-api-" + version + "-builder-image"
      params:
        additional_tags: tags/tags
        image: #@ builder.name + "-platform-api-" + version + "-rc-image/image.tar"
    #@ if not is_enterprise_builder(builder):
    - put: #@ builder.name + "-platform-api-" + version + "-cloudfoundry-builder-image"
      params:
        additional_tags: tags/tags
        image: #@ builder.name + "-platform-api-" + version + "-rc-image/image.tar"
    #@ end
    - put: version
      resource: #@ builder.version_key + "-version"
      params:
        bump: patch
  #@ end
#@ end

groups:
- name: all
  jobs:
  - pin-cnb-lifecycle-releases
#@ for version in data.values.supported_lifecycle_versions:
  #@ for builder in data.values.builders:
  - #@ "create-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "test-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "ship-{}-builder-platform-api-{}".format(builder.name, version)
  #@ end
#@ end

#@ for builder in data.values.builders:
- name: #@ builder.name + "-builder"
  jobs:
  #@ for version in data.values.supported_lifecycle_versions:
  - #@ "create-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "test-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "ship-{}-builder-platform-api-{}".format(builder.name, version)
  #@ end
#@ end

#@ for version in data.values.supported_lifecycle_versions:
- name: #@ "platform-api-" + version
  jobs:
  #@ for builder in data.values.builders:
  - #@ "create-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "test-{}-builder-rc-platform-api-{}".format(builder.name, version)
  - #@ "ship-{}-builder-platform-api-{}".format(builder.name, version)
  #@ end
#@ end
