#@data/values
---
concourse_url: https://buildpacks.ci.cf-app.com
cnb_builder_uri: git@github.com:paketo-buildpacks/builder
cnb_builder_private_key: ((builder-deploy-key.private_key))
destination_registry_username: _json_key
destination_registry_password: ((paketo-gcr-service-account-key))
supported_lifecycle_versions:
  - latest
  - n-1
  - n-2
images:
  - build
  - run
stacks:
- name: cflinuxfs3
  tag: full-cf
- name: bionic
  tag: base
- name: tiny
  tag: tiny
builders:
- name: tiny
  stack: tiny
  version_key: tiny
  repository: gcr.io/paketo-buildpacks/builder
  latest: false
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "org.cloudfoundry.stacks.tiny"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:tiny-cnb"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:tiny-cnb"
- name: base
  stack: bionic
  version_key: base
  repository: gcr.io/paketo-buildpacks/builder
  latest: false
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "io.buildpacks.stacks.bionic"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:base-cnb"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:base-cnb"
- name: full-cf
  stack: cflinuxfs3
  version_key: full-cf
  repository: gcr.io/paketo-buildpacks/builder
  latest: true
  builder_image_params:
  - name: REPO
    value: paketo-buildpacks/builder
  - name: STACK
    value: "org.cloudfoundry.stacks.cflinuxfs3"
  - name: BUILD_IMAGE
    value: "gcr.io/paketo-buildpacks/build:full-cnb-cf"
  - name: RUN_IMAGE
    value: "gcr.io/paketo-buildpacks/run:full-cnb-cf"
cnbs:
- name: nodejs
  git_repo: "https://github.com/paketo-buildpacks/nodejs"
  skip_stack:
    - "tiny"
- name: go
  git_repo: "https://github.com/paketo-buildpacks/go"
  skip_stack: []
- name: httpd
  git_repo: "https://github.com/paketo-buildpacks/httpd"
  skip_stack:
    - "bionic"
    - "tiny"
- name: nginx
  git_repo: "https://github.com/paketo-buildpacks/nginx"
  skip_stack:
    - "bionic"
    - "tiny"
- name: php
  git_repo: "https://github.com/paketo-buildpacks/php"
  skip_stack:
    - "bionic"
    - "tiny"
- name: dotnet-core
  git_repo: "https://github.com/paketo-buildpacks/dotnet-core"
  skip_stack:
    - "tiny"
published_cnbs:
- name: bellsoft-liberica
  skip_stack:
    - "tiny"
- name: build-system
  skip_stack:
    - "tiny"
- name: executable-jar
  skip_stack:
    - "tiny"
- name: azure-application-insights
  skip_stack:
    - "tiny"
- name: debug
  skip_stack:
    - "tiny"
- name: google-stackdriver
  skip_stack:
    - "tiny"
- name: jmx
  skip_stack:
    - "tiny"
- name: procfile
  skip_stack:
    - "tiny"
- name: apache-tomcat
  skip_stack:
    - "tiny"
- name: spring-boot
  skip_stack:
    - "tiny"
- name: dist-zip
  skip_stack:
    - "tiny"
- name: encrypt-at-rest
  skip_stack:
    - "tiny"
