---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
- name: bre-ci
- name: cf-deployment-concourse-tasks
- name: toolsmiths-env
outputs:
- name: cats-integration-config
run:
  path: bre-ci/tasks/create-cats-integration-config/run
