---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
  - name: core-deps-ci
  - name: platform-api-version
    optional: true
  - name: version
    optional: true

outputs:
  - name: tags

run:
  path: core-deps-ci/tasks/shared/write-tags-list/run

params:
  TAGS:
  STACK:
  REMOVE_CF_SUFFIX: false
  LATEST_PLATFORM_API: false
