---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: paketobuildpacks/build
    tag: base
inputs:
  - name: core-deps-ci
  - name: source
  - name: dependency
  - name: required_dependency_1
    optional: true
  - name: required_dependency_2
    optional: true
run:
  path: core-deps-ci/tasks/dep-builder/test-dependency/run
params:
  MIXINS:
