---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci

inputs:
- name: core-deps-ci
- name: tiny-run-base-dockerfile
- name: tiny-run-cnb-dockerfile

outputs:
- name: tiny-stack-receipt

run:
  path: core-deps-ci/tasks/stacks/write-tiny-stack-receipt/run
