---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci

inputs:
- name: bre-ci
- name: receipt
- name: receipt-s3

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BUCKET:
  RECEIPT_FILENAME:

run:
  path: bre-ci/tasks/check-for-receipt-diff/run
