---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
  - name: stacks
  - name: build-args
    optional: true
  - name: docker_creds
    optional: true

run:
  path: build

outputs:
  - name: image

params:
  CONTEXT:
  BUILD_ARGS_FILE:
  DOCKER_CONFIG: docker_creds
