---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
  - name: bre-ci
  - name: platform-api-version
    optional: true
  - name: version
    optional: true

outputs:
  - name: tags

run:
  path: bre-ci/tasks/write-tags-list/run

params:
  TAGS:
