---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
  - name: core-deps-ci
  - name: lifecycle-metadata-file
run:
  path: core-deps-ci/tasks/pin-lifecycle-versions/run
params:
  CONCOURSE_URL:
  CONCOURSE_USERNAME:
  CONCOURSE_PASSWORD:
  CONCOURSE_TEAM:
  PIPELINE_NAME:
