---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/bre-ci
inputs:
- name: bre-ci
- name: release
- name: buildpack-release-tarball
outputs:
- name: release
- name: release-tarball
- name: version
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
run:
  path: bre-ci/tasks/finalize-buildpack-release/run
