---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: coredeps/core-deps-ci
inputs:
- name: core-deps-ci
- name: cf-deployment-concourse-tasks
- name: toolsmiths-env
- name: release-tarball
run:
  path: core-deps-ci/tasks/upload-bosh-release/run
